server:
  port: 8080
  servlet:
    context-path: /api/orders-api

spring:
  application:
    name: Orders-API
  web:
    error:
      include-message: always
      include-exception: true
      include-binding-errors: always

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orders_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc.batch_size: 10
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        query.fail_on_pagination_over_collection_fetch: true
      jakarta.persistence.validation.mode: none

springdoc:
  #  api-docs: # TODO remove?
  #    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    root: INFO
    ru.rgrabelnikov.ordersapi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info, health, loggers
  info:
    git:
      mode: full
